package com.restaurante.bot.business.service;

import com.restaurante.bot.dto.PositionDto;
import com.restaurante.bot.dto.PositionSaveAndUpdateDto;
import com.restaurante.bot.business.interfaces.IPositionService;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.test.context.ActiveProfiles;
import org.springframework.transaction.annotation.Transactional;

import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertTrue;

@SpringBootTest
@ActiveProfiles("test")
@Transactional
public class PositionServiceIntegrationTest {

    @Autowired
    private IPositionService positionService;

    @Test
    void testSavePositionGeneratesId() {
        PositionSaveAndUpdateDto dto = new PositionSaveAndUpdateDto();
        dto.setDescription("Integration Test Position");
        dto.setStatus("ACTIVE");

        PositionDto saved = positionService.save(dto);

        assertNotNull(saved, "Saved PositionDto should not be null");
        assertNotNull(saved.getPositionId(), "ID should be generated by the XML mapping (IDENTITY)");
        assertTrue(saved.getPositionId() > 0, "Generated ID should be positive");
    }
}
