package com.restaurante.bot.business.service;

import com.restaurante.bot.dto.GgpUserSaveAndUpdateDto;
import com.restaurante.bot.dto.UserDto;
import com.restaurante.bot.model.*;
import com.restaurante.bot.repository.*;
import com.restaurante.bot.application.ports.incoming.UserUseCase;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.test.context.ActiveProfiles;
import org.springframework.transaction.annotation.Transactional;

import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertTrue;

@SpringBootTest
@ActiveProfiles("test")
@Transactional
public class UserServiceIntegrationTest {

    @Autowired
    private UserUseCase userService;

    @Autowired
    private RolRepository rolRepository;

    @Autowired
    private CompanyRepository companyRepository;

    @Autowired
    private PositionRepository positionRepository;

    @Autowired
    private AreaRepository areaRepository;

    private Long rolId;
    private Long companyId;
    private Long positionId;
    private Long areaId;

    @BeforeEach
    void setUp() {
        Rol rol = new Rol();
        rol.setName("ADMIN");
        rol.setStatus("ACTIVE");
        rol = rolRepository.save(rol);
        rolId = rol.getRolId();

        Company company = new Company();
        company.setName("Test Company");
        company.setStatus("ACTIVE");
        company = companyRepository.save(company);
        companyId = company.getId();

        Position position = new Position();
        position.setDescription("Tester");
        position.setStatus("ACTIVE");
        position = positionRepository.save(position);
        positionId = position.getPositionId();

        Area area = new Area();
        area.setDescription("QA");
        area.setStatus("ACTIVE");
        area = areaRepository.save(area);
        areaId = area.getAreaId();
    }

    @Test
    void testSaveUserGeneratesId() {
        GgpUserSaveAndUpdateDto dto = new GgpUserSaveAndUpdateDto();
        dto.setName("Integration Test User");
        dto.setEmail("test@integration.com");
        dto.setLogin("testuser");
        dto.setPassword("password123");
        dto.setRol(rolId);
        dto.setCompany(companyId);
        dto.setPosition(positionId);
        dto.setArea(areaId);
        dto.setStatus("ACTIVE");

        UserDto saved = userService.save(dto);

        assertNotNull(saved, "Saved UserDto should not be null");
        assertNotNull(saved.getUserId(), "User ID should be generated by the XML mapping (IDENTITY)");
        assertTrue(saved.getUserId() > 0, "Generated User ID should be positive");
    }
}
